name: Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Check Java version
        run: java -v

      - name: Check Maven version
        run: mvn -v

      - name: Build
        run: make
